--- #YAML:1.0
name:               Set-IntSpan-Fast
version:            1.15
abstract:           Fast handling of sets containing integer spans.
author:
    - Andy Armstrong <andy@hexten.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Types:  0
    List::Util:   0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
